<div id="portfolio-main" class="sc-portfolio">
    <button type="button" class="sc-btn up-btn">UP</button>
    <div class="pf-header">
        <div class="black-bg">
            <div class="content">
                <h1>서세찬의 포트폴리오</h1>
            </div>
            <div class="blank"></div>
            <div class="gnb">
                <ul class="sc-list-inline sc-clearfix">
                   <li>
                       <a href="#pf-introduce">소개</a>
                   </li>
                    <li>
                        <a href="#pf-skill">개발 스킬</a>
                    </li>
                    <li class="last">
                        <a href="#pf-portfolio">포트폴리오</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="pf-body sc-clearfix">
        <div class="sc-container">
            <div id="pf-introduce" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">소개</h2>
                </div>
                <div class="sc-row-body">
                    <div class="profile-box">
                        <div class="sc-media sc-media-md sc-clearfix">
                            <img src="../../assets/img/giraffe.png" />
                            <div class="sc-media-content">
                                <ul class="sc-hidden-md">
                                    <li>
                                        <p>진짜배기 개발자가 되기 위한 <strong class="passion">열정</strong></p>
                                    </li>
                                    <li>
                                        <p>스타트업에서 1년 6개월 간 다양한 컨셉의 프로젝트 개발 <strong class="experience">경험</strong></p>
                                    </li>
                                    <li>
                                        <p>어린 시절 운동선수 경험과 현재 종합격투기로 다져진 강한 <strong class="strength">체력</strong></p>
                                    </li>
                                    <li>
                                        <p>꾸준함과 성실함으로 탁월함을 만들기 위한 <strong class="effort">노력</strong></p>
                                    </li>
                                </ul>
                                <ul class="sc-hidden-sm">
                                    <li>
                                        <p>개발을 향한 <strong class="passion">열정</strong></p>
                                    </li>
                                    <li>
                                        <p>다양한 컨셉의 프로젝트 개발 <strong class="experience">경험</strong></p>
                                    </li>
                                    <li>
                                        <p>운동으로 다져진 강인한 <strong class="strength">체력</strong></p>
                                    </li>
                                    <li>
                                        <p>탁월함을 향한 <strong class="effort">노력</strong></p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pf-skill" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">개발 스킬</h2>
                </div>
                <div class="sc-row-body">
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">FRONT-END SKILL</h3>
                                <p class="character-desc">HTML/CSS+Bootstrap, Javascript+Jquery</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">BACK-END SKILL</h3>
                                <p class="character-desc">PHP+Phalcon, Mysql+Workbench, Nodejs+Express, Ubuntu</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">CVS TOOL</h3>
                                <p class="character-desc">Git+Github</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">협업 도구</h3>
                                <p class="character-desc">Gmail, Trello</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pf-portfolio" class="sc-row last">
                <div class="sc-row-header">
                    <h2 class="title">포트폴리오</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-carousel">
                        <button type="button" class="sc-btn sc-carousel-btn prev-btn"> < </button>
                        <button type="button" class="sc-btn sc-carousel-btn next-btn"> > </button>
                        <div class="pf-list">
                            <span class="blank"></span>
                            <div class="sc-row">
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item current">
                                    <div class="pf-item tuttoroom">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/tuttoroom">Tuttoroom</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">관계형 SNS 서비스</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item">
                                    <div class="pf-item bookk">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/bookk">Bookk</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">도서 출판 및 판매 플랫폼</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item">
                                    <div class="pf-item thehook">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/thehook">The Hook</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">태그 기반 SNS 서비스</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item">
                                    <div class="pf-item laughingbeans">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/laughingbean">Laughingbeans</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">외국어 학습 플랫폼</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-row">
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item">
                                    <div class="pf-item ipoptv">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/ipoptv">Ipoptv</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">댄스 중심의 문화 콘텐츠 웹 사이트</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item">
                                    <div class="pf-item moruwa">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/moruwa">Moruwa</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">반지 제작 웹 사이트</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item">
                                    <div class="pf-item peoplefund">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/peoplefund">Peoplefund</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">핀테크 대출/투자 플랫폼</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item">
                                    <div class="pf-item bookclip">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/bookclip">Bookclip</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">독서모임 SNS 서비스</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-row">
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item">
                                    <div class="pf-item postype">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/postype">Postype</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">1인 미디어 플랫폼 서비스</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="sc-col sc-col-sm-2 sc-col-md-4 sc-col-item">
                                    <div class="pf-item portfolio-site">
                                        <div class="pf-item-content">
                                            <h3 class="title"><a href="/portfolio/sschan">포트폴리오</a></h3>
                                            <span class="line"></span>
                                            <span class="desc">서세찬의 포트폴리오 사이트</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pf-footer">
        <div class="sc-container">
<!--            <p>Welcome. This is sschan's portfolio website. Have a nice day ^^</p>-->
            <p>환영합니다. 여기는 서세찬의 포트폴리오 사이트입니다.</p>
        </div>
    </div>
</div>
