<!--<div id="sc-carousel" class="sc-carousel">-->
<!--    <div class="item item-1 current">-->
<!--        <p>1</p>-->
<!--    </div>-->
<!--    <div class="item item-2">-->
<!--        <p>2</p>-->
<!--    </div>-->
<!--    <div class="item item-3">-->
<!--        <p>3</p>-->
<!--    </div>-->
<!--    <div class="item item-4">-->
<!--        <p>4</p>-->
<!--    </div>-->
<!--    <div class="item item-5">-->
<!--        <p>5</p>-->
<!--    </div>-->
<!--</div>-->
<!--<button class="prev-btn">이전</button>-->
<!--<button class="next-btn">다음</button>-->

<!--<button type="button" class="sc-btn file-load">파일로드테스트</button>-->
<!--<div id="test-image">-->
<!--</div>-->

