<div id="portfolio" class="sc-portfolio bookk">
    <div class="pf-header">
        <div class="black-bg">
            <div class="content">
                <h1>Bookk</h1>
            </div>
            <div class="blank"></div>
            <div class="gnb">
                <ul class="sc-list-inline sc-clearfix">
                   <li>
                       <a href="#pf-introduce">개요</a>
                   </li>
                    <li>
                        <a href="#pf-character">특징</a>
                    </li>
                    <li class="last">
                        <a href="#pf-solution">문제 해결 경험</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="pf-body sc-clearfix">
        <div class="sc-container">
            <div id="pf-introduce" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">개요</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-half sc-pull-left inline-center">
                        <div class="sc-spec-box">
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>Bookk (부크크)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">설명</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>도서 출판 및 판매 플랫폼</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">제작 기간</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>2014년 6월 ~ 2015년 1월 (8개월, 2차 개발 포함 일정)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">담당 및 기여도</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>프론트 엔드 (90%), 백엔드 (90%)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 스펙</span>
                                </div>
                                <div class="sc-spec-value">
                                    <ul>
                                        <li>
                                            <p><span>HTML/CSS + Bootstrap, Javascript + JQuery</span></p>
                                        </li>
                                        <li>
                                            <p><span>PHP + Phalcon, Mysql + Workbench</span></p>
                                        </li>
                                        <li>
                                            <p><span>Git + Github</span></p>
                                        </li>
                                        <li>
                                            <p><span>Gmail 및 Trello</span></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 주소</span>
                                    <span class="blank"></span>
                                </div>
                                <div class="sc-spec-value">
                                    <a href="http://bookk.co.kr" class="sc-btn pr-link-btn" target="_blank">사이트 방문 (web)</a>
                                    <a href="http://m.bookk.co.kr" class="sc-btn pr-link-btn" target="_blank">사이트 방문 (mobile)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-half sc-pull-left sc-hidden-lg">
                        <div class="pf-image"></div>
                    </div>
                </div>
            </div>

            <div id="pf-character" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">특징</h2>
                </div>
                <div class="sc-row-body">
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">결제 모듈 연동 (이니시스)</h3>
                                <p class="character-desc">웹, 모바일 결제 모듈 연동</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">daumeditor 사용</h3>
                                <p class="character-desc">부크크 커뮤니티의 에디터로 사용</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">html purifier 을 이용한 데이터 처리</h3>
                                <p class="character-desc">XSS 에 대한 보안 강화를 위해서 입력하는 데이터에 대한 처리</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">안드로이드 웹앱 개발</h3>
                                <p class="character-desc">m.bookk.co.kr 서브 도메인 사용</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">관리자 페이지를 통한 서비스 관리자 툴 개발</h3>
                                <p class="character-desc">사용자, 도서 관리 뿐만 아니라 주문, 결제, 정산에 대한 서비스 전반에 대한 관리</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">관리자 정산 내역 엑셀 파일로 추출</h3>
                                <p class="character-desc">excellentport js 사용 (<a href="https://github.com/jmaister/excellentexport" target="_blank">https://github.com/jmaister/excellentexport</a>)</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">KMC 본인인증 서비스 연동</h3>
                                <p class="character-desc">웹, 모바일 본인 인증 연동</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">구글 클라우드 메세지(GCM) 이용</h3>
                                <p class="character-desc">GCM을 이용해 사용자에게 관련 정보 알림 제공</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pf-solution" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">문제 해결 경험</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">서브 도메인 세션 유지</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>서브도메인의 m.bookk.co.kr 에 대한 세션 유지가 필요함.</p></li>
                                            <li><p>php의 session_set_cookie_params() 함수를 사용하여 서브 도메인과 쿠키를 공유하도록 설정.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">XSS 스크립트 보안 문제</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>사용 가능한 태그와 문자에 대해서 사전 기획 제안.</p></li>
                                            <li><p>php htmlpurifier(<a href="http://htmlpurifier.org/" target="_blank">http://htmlpurifier.org</a>) 적용하여 입력하는 데이터에 대한 처리.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pf-footer">

    </div>
</div>
