<div id="portfolio" class="sc-portfolio laughingbean">
    <div class="pf-header">
        <div class="black-bg">
            <div class="content">
                <h1>Laughingbean</h1>
            </div>
            <div class="blank"></div>
            <div class="gnb">
                <ul class="sc-list-inline sc-clearfix">
                   <li>
                       <a href="#pf-introduce">개요</a>
                   </li>
                    <li>
                        <a href="#pf-character">특징</a>
                    </li>
                    <li class="last">
                        <a href="#pf-solution">문제 해결 경험</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="pf-body sc-clearfix">
        <div class="sc-container">
            <div id="pf-introduce" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">개요</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-half sc-pull-left inline-center">
                        <div class="sc-spec-box">
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>Laughingbean (래핑빈)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">설명</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>외국어 학습 플랫폼 서비스</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">제작 기간</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>2014년 12월 ~ 2015년 03월 (3개월)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">담당 및 기여도</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>백엔드 개발 참여(40%)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 스펙</span>
                                </div>
                                <div class="sc-spec-value">
                                    <ul>
                                        <li>
                                            <p><span>HTML/CSS, Javascript + JQuery</span></p>
                                        </li>
                                        <li>
                                            <p><span>PHP + Phalcon, Mysql + Workbench</span></p>
                                        </li>
                                        <li>
                                            <p><span>Git + Github</span></p>
                                        </li>
                                        <li>
                                            <p><span>Gmail 및 Trello</span></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 주소</span>
                                    <span class="blank"></span>
                                </div>
                                <div class="sc-spec-value">
                                    <a href="http://laughingbeans.com" class="sc-btn pr-link-btn" target="_blank">사이트 방문</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-half sc-pull-left sc-hidden-lg">
                        <div class="pf-image"></div>
                    </div>
                </div>
            </div>

            <div id="pf-character" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">특징</h2>
                </div>
                <div class="sc-row-body">
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">유투브 영상을 이용한 외국어 학습</h3>
                                <p class="character-desc">YouTube Javascript API를 이용해 필요한 작업 진행</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">관리자 페이지 개발</h3>
                                <p class="character-desc">래핑빈 서비스를 관리할 수 있는 관리자 페이지 개발</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">다른 서비스 아이디 로그인 지원</h3>
                                <p class="character-desc">페이스북, 구글 로그인</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pf-solution" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">문제 해결 경험</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">단어, 문장 음성 지원</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>voicerss API(http://www.voicerss.org) 적용.</p></li>
                                            <li><p>현재는 래핑빈에서 해당 기능을 서비스 하지 않고 있음.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">단어 번역 지원</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>구글 번역 API 적용.</p></li>
                                            <li><p>현재는 래핑빈에서 해당 기능을 서비스 하지 않고 있음.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pf-footer">

    </div>
</div>
