<div id="portfolio" class="sc-portfolio moruwa">
    <div class="pf-header">
        <div class="black-bg">
            <div class="content">
                <h1>Moruwa</h1>
            </div>
            <div class="blank"></div>
            <div class="gnb">
                <ul class="sc-list-inline sc-clearfix">
                   <li>
                       <a href="#pf-introduce">개요</a>
                   </li>
                    <li>
                        <a href="#pf-character">특징</a>
                    </li>
                    <li class="last">
                        <a href="#pf-solution">문제 해결 경험</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="pf-body sc-clearfix">
        <div class="sc-container">
            <div id="pf-introduce" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">개요</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-half sc-pull-left inline-center">
                        <div class="sc-spec-box">
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>Moruwa (모루와)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">설명</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>반지 제작 웹 사이트</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">제작 기간</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>2015년 01월 ~ 2015년 02월 (2개월)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">담당 및 기여도</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>프론트 엔드(70%) 백엔드(100%)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 스펙</span>
                                </div>
                                <div class="sc-spec-value">
                                    <ul>
                                        <li>
                                            <p><span>HTML/CSS + Bootstrap, Javascript + JQuery</span></p>
                                        </li>
                                        <li>
                                            <p><span>PHP + Phalcon, Mysql + Workbench</span></p>
                                        </li>
                                        <li>
                                            <p><span>Git + Github</span></p>
                                        </li>
                                        <li>
                                            <p><span>Gmail 및 Trello</span></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 주소</span>
                                    <span class="blank"></span>
                                </div>
                                <div class="sc-spec-value">
                                    <a href="http://www.moruwa.co.kr" class="sc-btn pr-link-btn" target="_blank">사이트 방문</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-half sc-pull-left sc-hidden-lg">
                        <div class="pf-image"></div>
                    </div>
                </div>
            </div>

            <div id="pf-character" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">특징</h2>
                </div>
                <div class="sc-row-body">
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">셀프 디자인 시뮬레이션</h3>
                                <p class="character-desc">세가지(큐빅, 링, 색상) 를 선택하여 각각의 옵션이 제공하는 디자인을 조합하여 셀프 디자인 적용</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">관리자 페이지 개발</h3>
                                <p class="character-desc">사이트의 기본적인 관리자 페이지 개발</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">NAVER Editor 적용</h3>
                                <p class="character-desc">관리자 페이지의 에디터 NAVER Editor 사용</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">SNS 공유하기</h3>
                                <p class="character-desc">페이스북, 트위터, 구글 플러스, 텀블러, 핀터레스트 공유하기 제공</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">반응형 웹 사이트</h3>
                                <p class="character-desc">다양한 브라우저와 기기에 최적화 된 반응형 웹 사이트</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pf-solution" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">문제 해결 경험</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">셀프 디자인 시뮬레이션</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>서버에 옵션에 맞게 폴더와 파일 이름 지정.</p></li>
                                            <li><p>각각의 옵션을 단계별로 선택하게 유도 함으로써 서버에 저장된 해당 이미지를 보여주는 방식.</p></li>
                                            <li><p>회원가입 방식의 사이트가 아니기 때문에 유일한 URL을 생성하여 제공하는 방식으로 개발 진행.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pf-footer">

    </div>
</div>
