<div id="portfolio" class="sc-portfolio postype">
    <div class="pf-header">
        <div class="black-bg">
            <div class="content">
                <h1>Postype</h1>
            </div>
            <div class="blank"></div>
            <div class="gnb">
                <ul class="sc-list-inline sc-clearfix">
                   <li>
                       <a href="#pf-introduce">개요</a>
                   </li>
                    <li>
                        <a href="#pf-character">특징</a>
                    </li>
                    <li class="last">
                        <a href="#pf-solution">문제 해결 경험</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="pf-body sc-clearfix">
        <div class="sc-container">
            <div id="pf-introduce" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">개요</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-half sc-pull-left inline-center">
                        <div class="sc-spec-box">
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>Postype (포스타입)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">설명</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>1인 미디어 플랫폼 서비스</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">개발 참여</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>2015년 7월 ~ 2015년 9월 (3개월)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">담당 및 기여도</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>3달간 메인 개발자로 개발 담당</span>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 스펙</span>
                                </div>
                                <div class="sc-spec-value">
                                    <ul>
                                        <li>
                                            <p><span>HTML/CSS, Javascript + JQuery</span></p>
                                        </li>
                                        <li>
                                            <p><span>PHP + Phalcon, Mysql + Workbench</span></p>
                                        </li>
                                        <li>
                                            <p><span>Git + Github</span></p>
                                        </li>
                                        <li>
                                            <p><span>Gmail 및 Trello</span></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 주소</span>
                                    <span class="blank"></span>
                                </div>
                                <div class="sc-spec-value">
                                    <a href="http://postype.com" class="sc-btn pr-link-btn" target="_blank">사이트 방문</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-half sc-pull-left sc-hidden-lg">
                        <div class="pf-image"></div>
                    </div>
                </div>
            </div>

            <div id="pf-character" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">개발 내용</h2>
                </div>
                <div class="sc-row-body">
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">가상 화폐(포인트) 기능 개발</h3>
                                <p class="character-desc">포인트를 이용한 가상 화폐 관련 기능 개발</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">결제 시스템 개발</h3>
                                <p class="character-desc">페이게이트 결제 API 연동</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">포스트 관리 개발</h3>
                                <p class="character-desc">포스트 삭제, 카테고리 변경 등의 포스트 관리에 대한 기능 개발</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">포스트 목록 초기화 개선</h3>
                                <p class="character-desc">포스트 목록이 초기화 되는 문제 개선</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pf-solution" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">문제 해결 경험</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">포스트 목록 초기화 시점 작업 개선</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>포스트 목록에서 포스트의 상세페이지 이동 후 목록으로 다시 돌아오는 경우 기존에 불러왔던 목록이 아니라 초기화 되서 처음 부터 보여주는 사용성 문제 인식</p></li>
                                            <li><p>포스트 상세 페이지에 접근하는 경우 이전 페이지에 대한 정보를 세션에 저장하여 상세페이지에서 바로 목록을 되돌아가는 경우에 한해서 세션을 이용할 수 있도록 진행</p></li>
                                            <li><p>현재 포스타입은 페이지네이션 방식으로 포스트 목록으로 변경한 상태.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pf-footer">

    </div>
</div>
