<div id="portfolio" class="sc-portfolio sschan">
    <div class="pf-header">
        <div class="black-bg">
            <div class="content">
                <h1>SSCHAN's Portfolio</h1>
            </div>
            <div class="blank"></div>
            <div class="gnb">
                <ul class="sc-list-inline sc-clearfix">
                   <li>
                       <a href="#pf-introduce">개요</a>
                   </li>
                    <li>
                        <a href="#pf-character">특징</a>
                    </li>
                    <li class="last">
                        <a href="#pf-solution">문제 해결 경험</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="pf-body sc-clearfix">
        <div class="sc-container">
            <div id="pf-introduce" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">개요</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-half sc-pull-left inline-center">
                        <div class="sc-spec-box">
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>개인 포트폴리오 사이트</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">설명</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>지금까지 진행했던 프로젝트를 정리하기 위한 개인 사이트 제작</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">제작 기간</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>2016년 1월 23일 ~ 2014년 1월 26일 (4일)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">담당 및 기여도</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>프론트 엔드 (100%)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 스펙</span>
                                </div>
                                <div class="sc-spec-value">
                                    <ul>
                                        <li>
                                            <p><span>HTML/CSS, Javscript + JQuery</span></p>
                                        </li>
                                        <li>
                                            <p><span>PHP + Phalcon</span></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 주소</span>
                                    <span class="blank"></span>
                                </div>
                                <div class="sc-spec-value">
                                    <a href="/" class="sc-btn pr-link-btn" target="_blank">사이트 방문</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-half sc-pull-left sc-hidden-lg">
                        <div class="pf-image"></div>
                    </div>
                </div>
            </div>

            <div id="pf-character" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">특징</h2>
                </div>
                <div class="sc-row-body">
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">디자인 부터 개발까지 모두 담당</h3>
                                <p class="character-desc">사이트 디자인 및 마크업 부터 스크립트 까지 직접 계획 및 제작해서 개발</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">캐러셀 라이브러리 제작</h3>
                                <p class="character-desc">모바일에서 표시되는 캐러셀을 라이브러리로 제작해서 사용</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">반응형 웹 사이트</h3>
                                <p class="character-desc">접속하는 기기에 맞춰 정보 표시</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">IE 9 이상 브라우저에 최적화</h3>
                                <p class="character-desc">Chrome, Firefox, Safari, Opera, IE 9 이상 브라우저에서 동일하게 표시</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pf-solution" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">문제 해결 경험</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">서랍 메뉴 스크립트에 메모이제이션(Memoization) 패턴 적용</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li>
                                                <p>서랍 메뉴가 열리는 경우 서랍 메뉴 뒷 부분의 영역이 고정될 수 있도록 작업 진행</p>
                                            </li>
                                            <li>
                                                <p>위치를 고정 시키기 위해서는 scroll top 위치가 필요하지만 position:fixed를 하게 되면 scrollTop은 초기화 되는 문제</p>
                                            </li>
                                            <li>
                                                <p>함수에 메모이제이션 패턴 적용하여 scrollTop 값을 저장하도록 함으로써 해결</p>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">IE 9 에서의 height: 100% 문제</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li>
                                                <p>IE 9 에서는 height 값을 퍼센트로 사용하기 위해서는 html과 body에 height: 100%를 지정해 줄 필요가 있음</p>
                                            </li>
                                            <li>
                                                <p>html, body 뿐만 아니라 부모의 엘리먼트 요소에도 height에 퍼센트 값을 지정</p>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">IE 9 CSS Transition 문제</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li>
                                                <p>캐러셀 라이브러리 제작 시 IE 9 버전에서 처리 문제</p>
                                            </li>
                                            <li>
                                                <p>IE 9 이하부터는 transition이 지원되지 않음.</p>
                                            </li>
                                            <li>
                                                <p>라이브러리 에서는 transition의 지원 여부에 따라서 분기 처리</p>
                                            </li>
                                            <li>
                                                <p>IE 9 이하에서도 애니메이션 처리할 수 있는 라이브러리는 존재 (<a href="http://louisremi.github.io/jquery.transition.js/test/index.html" target="_blank" >http://louisremi.github.io/jquery.transition.js/test/index.html</a>)</p>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pf-footer">
    </div>
</div>
