<div id="portfolio" class="sc-portfolio thehook">
    <div class="pf-header">
        <div class="black-bg">
            <div class="content">
                <h1>The Hook</h1>
            </div>
            <div class="blank"></div>
            <div class="gnb">
                <ul class="sc-list-inline sc-clearfix">
                   <li>
                       <a href="#pf-introduce">개요</a>
                   </li>
                    <li>
                        <a href="#pf-character">특징</a>
                    </li>
                    <li class="last">
                        <a href="#pf-solution">문제 해결 경험</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="pf-body sc-clearfix">
        <div class="sc-container">
            <div id="pf-introduce" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">개요</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-half sc-pull-left inline-center">
                        <div class="sc-spec-box">
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>The Hook (더후크)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">설명</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>태그 기반 추천 SNS 서비스</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">제작 기간</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>2014년 10월 ~ 2014년 12월 (3개월)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">담당 및 기여도</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>백엔드 API 개발(100%)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 스펙</span>
                                </div>
                                <div class="sc-spec-value">
                                    <ul>
                                        <li>
                                            <p><span>HTML/CSS</span></p>
                                        </li>
                                        <li>
                                            <p><span>PHP + Phalcon, Mysql + Workbench</span></p>
                                        </li>
                                        <li>
                                            <p><span>Git + Github</span></p>
                                        </li>
                                        <li>
                                            <p><span>Gmail 및 Trello</span></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 주소</span>
                                    <span class="blank"></span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>Apple store (현재 앱을 내린 상태)</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-half sc-pull-left sc-hidden-lg">
                        <div class="pf-image"></div>
                    </div>
                </div>
            </div>

            <div id="pf-character" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">특징</h2>
                </div>
                <div class="sc-row-body">
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">히든 링크 알고리즘</h3>
                                <p class="character-desc">포스트와 포스트, 사용자와 사용자의 연결고리 찾기</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">tag 기반 포스트 추천</h3>
                                <p class="character-desc">포스트에 사용된 테그를 바탕으로 연관된 포스트를 세 가지씩 지속적으로 추천</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">레벨 시스템</h3>
                                <p class="character-desc">사용자의 활동에 따른 경험치 부여, 레벨 시스템 적용</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">다른 서비스 아이디 로그인 지원</h3>
                                <p class="character-desc">페이스북, 구글 로그인</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">관리자 페이지 개발</h3>
                                <p class="character-desc">사용자, 포스트 등 기본적인 관리자 페이지 개발</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">다국어 지원</h3>
                                <p class="character-desc">한국어, 중국어, 영어, 인도네시아어,  태국어, 베트남어</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">모바일 알림 메세지 전송</h3>
                                <p class="character-desc">APNS를 이용한 알림 전송</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pf-solution" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">문제 해결 경험</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">추천 알고리즘 속도 개선</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>Phalcon 프레임 워크에서 제공하는 방식으로 쿼리를 사용했을 때 쿼리의 속도가 현저하게 떨어져 사용성이 매우 나쁘게 나타남.</p></li>
                                            <li><p>기존에 작성된 프레임워크 친화적인 코드를 네이티브 php 형식으로 쿼리로 변경하여 객체를 가져 오도록 개선.</p></li>
                                            <li><p>더 빠르게 진행하기 위해선 알고리즘에 맞게 데이터 모델링을 다시 진행 할 필요가 있다고 판단.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pf-footer">

    </div>
</div>
