<div id="portfolio" class="sc-portfolio tuttoroom">
    <div class="pf-header">
        <div class="black-bg">
            <div class="content">
                <h1>Tuttoroom</h1>
            </div>
            <div class="blank"></div>
            <div class="gnb">
                <ul class="sc-list-inline sc-clearfix">
                   <li>
                       <a href="#pf-introduce">개요</a>
                   </li>
                    <li>
                        <a href="#pf-character">특징</a>
                    </li>
                    <li class="last">
                        <a href="#pf-solution">문제 해결 경험</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="pf-body sc-clearfix">
        <div class="sc-container">
            <div id="pf-introduce" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">개요</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-half sc-pull-left inline-center">
                        <div class="sc-spec-box">
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>Tuttoroom (튜토룸)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">설명</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>관심사 기반의 룸을 생성하여 정보를 공유하는 SNS 서비스</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">제작 기간</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>2014년 3월 ~ 2014년 8월 (6개월)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row sc-clearfix">
                                <div class="sc-spec-category">
                                    <span class="spec-name">담당 및 기여도</span>
                                </div>
                                <div class="sc-spec-value">
                                    <span>프론트 엔드 (90%), 백엔드 (90%)</span>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 스펙</span>
                                </div>
                                <div class="sc-spec-value">
                                    <ul>
                                        <li>
                                            <p><span>HTML/CSS + Bootstrap, Javascript + JQuery</span></p>
                                        </li>
                                        <li>
                                            <p><span>PHP + Phalcon, Mysql + Workbench</span></p>
                                        </li>
                                        <li>
                                            <p><span>Git + Github</span></p>
                                        </li>
                                        <li>
                                            <p><span>Gmail 및 Trello</span></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sc-spec-row">
                                <div class="sc-spec-category">
                                    <span class="spec-name">프로젝트 주소</span>
                                    <span class="blank"></span>
                                </div>
                                <div class="sc-spec-value">
                                    <a href="http://tuttoroom.com" class="sc-btn pr-link-btn" target="_blank">사이트 방문</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-half sc-pull-left sc-hidden-lg">
                        <div class="pf-image"></div>
                    </div>
                </div>
            </div>

            <div id="pf-character" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">특징</h2>
                </div>
                <div class="sc-row-body">
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">AWS(아마존 웹 서비스) 이용</h3>
                                <p class="character-desc">오레곤 지역으로 EC2와 S3를 이용</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">반응형 SNS</h3>
                                <p class="character-desc">페이스 북과 텀블러와의 차별점으로 반응형 SNS로 개발 진행</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">다국어 지원</h3>
                                <p class="character-desc">다국어(한국어, 영어, 중국어)에 맞춘 정보 표시 제공</p>
                            </div>
                        </div>
                    </div>
                    <div class="character-box">
                        <div class="sc-panel">
                            <div class="sc-panel-body sc-character-line">
                                <h3 class="character-title">관리자 페이지 개발</h3>
                                <p class="character-desc">관리자 페이지를 통한 사용자 및 포스트 관리 서비스 관리 개발</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pf-solution" class="sc-row">
                <div class="sc-row-header">
                    <h2 class="title">문제 해결 경험</h2>
                </div>
                <div class="sc-row-body">
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">DIV의 background-image의 display: none인 경우 이미지 로드 이슈</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>background-image를 지정하고 display: none도 함께 적용했을때 이미지 로드가 발생하지 않는다는 정보 접했음.</p></li>
                                            <li><p>테스트를 진행한 결과 이미지 로드가 발생.</p></li>
                                            <li><p>data-* attribute 형식으로 태그에 URL을 저장하고 사용하는 방법으로 변경.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">다국어 지원</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>language 클래스 파일을 생성하여 언어셋을 생성.</p></li>
                                            <li><p>phalcon 에서 제공하는 getBestLanguage() 함수를 적용 ($_SERVER[‘HTTP_ACCEPT_LANGUAGE’]와 동일한 동작) 해서 사용자의 언어를 확인 후 적절한 언어셋으로 설정.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">포스트 자동 삭제</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>포스트에 대한 사용자의 평가에 따라서 포스트의 등급이 부여되도록 기획.</p></li>
                                            <li><p>가장 낮은 등급의 포스트는 정해진 시간 이후에 삭제 되어야 함.</p></li>
                                            <li><p>crontab을 이용해 주기적으로 포스트의 등급 상태를 판단 및 삭제 하도록 진행.</p></li>
                                            <li><p>초기 서비스에서 해당 작업이 많이 필요 하지 않을 것으로 판단 하여 포스트가 호출 될 경우에 포스트의 등급 상태를 판단 하도록 변경</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">S3 연동 문제</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li>
                                                <p>AWS S3 연결을 위한 PHP S3 라이브러리 사용 (<a href="http://undesigned.org.za/2007/10/22/amazon-s3-php-class/" target="_blank">http://undesigned.org.za/2007/10/22/amazon-s3-php-class</a>)</p>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sc-solution-box">
                        <div class="sc-panel">
                            <div class="sc-panel-header">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/question.png" />
                                    <div class="sc-media-content">
                                        <h3 class="title">로그인 보안 문제</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="sc-panel-body">
                                <div class="sc-media sc-clearfix">
                                    <img src="../../assets/img/checkbox.png" />
                                    <div class="sc-media-content">
                                        <ul>
                                            <li><p>사용자 편의를 위해서 로그인 시 입력하는 정보(아이디, 비밀번호) 중 잘못된 정보를 명시하여 알려주는 방식을 사용.</p></li>
                                            <li><p>틀린정보를 명시하여 알려주는 방식을 사용했을 경우 (ex> 아이디가 틀렸습니다, 비밀번호가 틀렸습니다.) 아이디와 비밀번호를 알아내기 위한 해커의 노력을 줄이는 효과를 유발 할 수 있다고 판단.</p></li>
                                            <li><p>틀린 정보를 추상적으로 알려주는 방식으로 변경.</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
<!--            <div class="sc-row last">-->
<!--                <div class="sc-row-header">-->
<!--                    <h2 class="title">포트폴리오 더보기</h2>-->
<!--                </div>-->
<!--                <div class="sc-row-body">-->
<!--                    <div class="pf-related-section sc-clearfix">-->
<!--                        <div class="sc-half sc-clearfix">-->
<!--                            <div class="pf-section prev-section">-->
<!--                                <span class="badge">2016년</span>-->
<!--                                <div class="sc-media sc-clearfix">-->
<!--                                    <img src="../../assets/img/portfolio-bg.png" />-->
<!--                                    <div class="sc-media-content">-->
<!--                                        <h3 class="title">서세찬의 포트폴리오</h3>-->
<!--                                        <p>이직을 준비하며서 그동안 작업하 프로젝트를 정리하고 앞으로 진행하는 프로젝트들을 정리할 예정으로 만든 프로젝트</p>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="sc-half sc-clearfix">-->
<!--                            <div class="pf-section next-section">-->
<!--                                <span class="badge">2014년</span>-->
<!--                                <div class="sc-media sc-clearfix">-->
<!--                                    <img src="../../assets/img/bookk-main.png" />-->
<!--                                    <div class="sc-media-content">-->
<!--                                        <h3 class="title">Bookk(부크크)</h3>-->
<!--                                        <p>글을 쓰는 누구나 무료로 책을 출판(디자인, 인쇄, 배송)하고 판매할 수 있는 도서 출판 플랫폼 서비스</p>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->

        </div>
    </div>
    <div class="pf-footer">

    </div>
</div>
