<!DOCTYPE html >
<?php
/**
 * @var $list_category string
 * @var $category_name string
 */
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <title>Practice</title>
        <?php $this->assets->outputCss(); ?>
        <!--[if lt IE 9]>
            <script src="/assets/js/html5shiv.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- body content section -->
        <header>
            <h1>This is HTML5 TEST.</h1>
        </header>

        <?php echo $this->getContent(); ?>

        <footer></footer>

        <!-- javascript load section -->
        <?php $this->assets->outputJs(); ?>
    </body>
</html>